version: '4.0'

services:
  keeper:
    build: ./
    command: ./keeper
    ports:
      - 3200:3200
    depends_on:
      - db
    environment:
      - DATABASE_DSN=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - HOST=:3200


  db:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data